app: money-mind-v1-apis
service: money-mind-v1-apis

provider:
  name: aws
  stage: prod
  timeout: 29
  region: ap-south-1
  runtime: nodejs20.x
  memorySize: 512
  profile: ${env:AWS_PROFILE, 'money-mind-server'}
  environment:
    NODE_ENV: 'prod'
    PORT: 8000
    DB_NAME: ${ssm:/money-mind/prod/DB_NAME}
    DB_URL: ${ssm:/money-mind/prod/DB_URL}
    JWT_SECRET_KEY: ${ssm:/money-mind/prod/JWT_SECRET_KEY}
    GITHUB_TOKEN: ${ssm:/money-mind/prod/GITHUB_TOKEN, ''}
    GITHUB_MODEL: ${ssm:/money-mind/prod/GITHUB_MODEL, 'gpt-4o'}
    ENVIRONMENT: 'prod'
    SERVER: 'deploy'

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    external:
      - '@aws-sdk/*'

functions:
  management-api:
    handler: src/handler.debtmanagementapi
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Accept
              - Origin
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - acccessToken
              - accesstoken
            allowCredentials: false

      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Authorization
              - Accept
              - Origin
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Headers
              - acccessToken
              - accesstoken
            allowCredentials: false
